[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "cdc-places-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.9.4",
    "pandas>=2.3.1",
    "requests>=2.32.4",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
